version: "3.1"
services:
  app:
    build: .
    ports:
      - 8080:8080
    env_file:
      - server.env
  cache:
    image: redis
    env_file:
      - server.env
    
  db:
    image: postgres
    env_file:
      - server.env
    ports:
      - 5432:5432
    volumes:
      - db:/var/lib/postgresql/data
volumes:
  db: